stages: 
  - build

variables:
    DOCKER_TLS_CERTDIR: "/certs/client"

build-push-ecr:
  image: docker:latest
  stage: build
  services: 
    - docker:dind
  id_tokens:
    MY_OIDC_TOKEN:
      aud: https://devops-gitlab.inno.ws
  before_script:
    - apk add --no-cache aws-cli jq
    - echo "Checking OIDC Token..."
    - echo "Token length is ${#MY_OIDC_TOKEN}"
    - |
      CREDS=$(aws sts assume-role-with-web-identity \
        --role-arn ${ECS_ROLE_ARN} \
        --role-session-name "GitLabRunner-${CI_PIPELINE_ID}" \
        --web-identity-token ${MY_OIDC_TOKEN} \
        --duration-seconds 900 \
        --region ${AWS_DEFAULT_REGION})
    - export AWS_ACCESS_KEY_ID=$(echo ${CREDS} | jq -r '.Credentials.AccessKeyId')
    - export AWS_SECRET_ACCESS_KEY=$(echo ${CREDS} | jq -r '.Credentials.SecretAccessKey')
    - export AWS_SESSION_TOKEN=$(echo ${CREDS} | jq -r '.Credentials.SessionToken')
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_URL}
  script:
    - |
      cd app/
      docker build -t $ECR_URL/publisher:latest .
      docker push $ECR_URL/publisher:latest
